# Generated by Django 4.2.5 on 2023-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sports', '0002_sport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='match_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
