# Generated by Django 4.2.6 on 2023-10-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sports', '0002_sport_description'),
        ('app_general', '0002_subscription_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sports.sport'),
        ),
    ]
