# Generated by Django 4.2.6 on 2023-11-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('unapproved', 'Unapproved'), ('approved', 'Approved'), ('banned', 'Banned')], default='unapproved', max_length=20),
        ),
    ]
